version: 2
jobs:
  build:
    docker:
      - image: node:7.10.0
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - run: npm install
      - run: npm test
    working_directory: ~/ozymandias
